---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="alpine" tag="latest"
    - image="alpine" tag="edge"
    - image="amazonlinux" tag="1"
    - image="centos" tag="7"
    - image="centos" tag="latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "VMd40mpu+Sk26dFXI2B5Nzf0ztVdaQXfV5gz/PMMARZ3i637B5EbYNI+iy+svsZu0KjgJf3FxcKHqVQBJrlXiyvWLlvNA8stg3sud/3FuI61ccoFZTuFeuVE+U5/teqlWtSC8qJuW2qTCPlvrrzZVsSSuKicrmlQGyVDDMGB/DyEcpNefPZYnjhb2NS4uG0KOZYiObasa6HEg9Z2RmcDFMU/NLfne3qTtiXtCpCu3bZch96cwBi5jYw3i1fwRY8x373OCeTvuA5vfyoWL1qDOMwL4iguUJ+5qZPpRe4+YQUr9Ru/4L+gjSVIquL79/QSJAcomWfM9361eOETLBhYzgnm60zAKfyAns9hEsKhGybSpH96MyFhxEPGx+UsWO0gemAhPWERV7dbT8aaWtOVBT3dZ/JBSDot7b7ozsAVPVWlsHaBwYrIRVTo2IeI0DAKl1YxFqwwnAm3Q+QdSJ2kO5o59Mzi13YWgiZG16hPlAZmZ3MDxirKegWEpS2q4exImEL4Zx12HAtKy63FMBSMNu3fJ7jHQKWpzSghODHcHmePvBzelXngK6WxmRxqdqCJJeNW56Nf8gFr7SARZRzukXNF5d9uCnreM7j0pxQfb9f95bQ+9pjO2BCl1fekCWz62awphWhgwT14vSPIGz16cCFubr95icfzt342Q9gLfUQ="
  email: false
