---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="alpine" tag="latest"
    - image="alpine" tag="edge"
    - image="amazonlinux" tag="1"
    - image="centos" tag="7"
    - image="centos" tag="latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: "pQprV/efNdr5uoA89VCCtO3lpQTmBCqoDqzbTDMU6rzcb57vHg8sguCsZwNqQYOFXbG96eHoJpOFxifTbYW2LxYxTYGS9ISoVIOfz3CdiqrqgH79REHdONq0c0Y9tjZ8npbM9NtQW+Sfg4ctLjOmsoZMRgNwQ9xFiEs444FN7IrDir1pVs4ltIlvHp2HHotvxvH4XEWuXoRm8cWVg2rx5nBHoyYQ0bi/Lfd+C5bnnqU+fMeU/iJKWpj7b+d8ivtLqkIMorgGN+WJhTnrAJg4q7KAdoRPvJhUJLcH/Jsox0l7bfe0nJp2RITUathlBnJWUbvRI7ZabyJzlQeDlZCNNJ0gmgBF21qPPeGgibotJAq8TvI9A/bcTQ8EFpzZDhYz4wxi6iIM6nBTcuQ0ji8BPcGz5w3l8RsastTOfefIgTzuV1ev7dK2pvAGQCcz646Kxfa8cE7Wb+braytY7uR/5GbWjysHkHQWf3WYEMyFszCl66jX3CQq7rjOCs9jYG/IWWlIbebux+kNF0cWKxZ1CHaSDvRkI6wCuheBDMWfBAygKN0V45k168Rpi8nfXcGVILOX3iXvvJvFHVvy/OsJhq3v/K0pebH3VOQ0P/DcfFH0EJUMm/zhp4V8Fzj9pjkAnE6XdEx0f2msJECopZwZZggyomWoXZLY2ReaMgMzdt0="
  email: false
