---

- name: assert | Test if gotop_version is set correctly
  ansible.builtin.assert:
    that:
      - gotop_version is defined
      - gotop_version is string
    quiet: yes

- name: assert | Test if gotop_installation_path is set correctly
  ansible.builtin.assert:
    that:
      - gotop_installation_path is defined
      - gotop_installation_path is string
    quiet: yes
