---
- name: test if gotop_version is set correctly
  assert:
    that:
      - gotop_version is defined
    quiet: yes

- name: test if gotop_installation_path is set correctly
  assert:
    that:
      - gotop_installation_path is defined
    quiet: yes
