---
# tasks file for gotop

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install software
  ansible.builtin.unarchive:
    src: "{{ gotop_download_url }}"
    dest: "{{ gotop_installation_path }}"
    remote_src: yes
    mode: "0755"
